-- ─────────────────────────────────────────
-- CREATE TABLES
-- ─────────────────────────────────────────

-- ─────────────────────────────────────────
-- 1. CUSTOMERS
-- ─────────────────────────────────────────
CREATE TABLE IF NOT EXISTS customers (
  customer_id      INTEGER      NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
  customer_name    VARCHAR(255) NOT NULL,
  customer_email   VARCHAR(255) NOT NULL UNIQUE,
  customer_address VARCHAR(255) NOT NULL,
  customer_phone   VARCHAR(20)  NOT NULL,
  PRIMARY KEY (customer_id)
);

-- ─────────────────────────────────────────
-- 2. SUPPLIERS
-- ─────────────────────────────────────────
CREATE TABLE IF NOT EXISTS suppliers (
  supplier_id    INTEGER      NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
  supplier_name  VARCHAR(255) NOT NULL UNIQUE,
  supplier_email VARCHAR(255) NOT NULL UNIQUE,
  PRIMARY KEY (supplier_id)
);

-- ─────────────────────────────────────────
-- 3. CATEGORIES
-- ─────────────────────────────────────────
CREATE TABLE IF NOT EXISTS categories (
  category_id   INTEGER      NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
  category_name VARCHAR(255) NOT NULL UNIQUE,
  PRIMARY KEY (category_id)
);

-- ─────────────────────────────────────────
-- 4. PRODUCTS
-- unit_price : precio de catálogo del producto
-- quantity   : stock disponible (inventario)
-- ─────────────────────────────────────────
CREATE TABLE IF NOT EXISTS products (
  product_sku  VARCHAR(100)  NOT NULL UNIQUE,
  product_name VARCHAR(255)  NOT NULL,
  unit_price   NUMERIC(14,2) NOT NULL,
  quantity     INTEGER       NOT NULL DEFAULT 0,
  category_id  INTEGER       NOT NULL,
  PRIMARY KEY (product_sku),
  FOREIGN KEY (category_id) REFERENCES categories (category_id)
    ON UPDATE CASCADE ON DELETE RESTRICT
);

-- ─────────────────────────────────────────
-- 5. TRANSACTIONS
-- item_id        : PK autoincremental (un transaction_id
--                  tiene múltiples filas, una por producto)
-- unit_price     : precio real al momento de la venta
--                  (puede diferir del catálogo)
-- quantity       : unidades vendidas en esa línea
-- total_line_value: unit_price × quantity de la venta
-- ─────────────────────────────────────────
CREATE TABLE IF NOT EXISTS transactions (
  item_id          INTEGER       NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
  transaction_id   VARCHAR(100)  NOT NULL,
  transaction_date DATE          NOT NULL,
  customer_id      INTEGER       NOT NULL,
  product_sku      VARCHAR(100)  NOT NULL,
  supplier_id      INTEGER       NOT NULL,
  quantity         INTEGER       NOT NULL CHECK (quantity > 0),
  unit_price       NUMERIC(14,2) NOT NULL,
  total_line_value NUMERIC(14,2) NOT NULL,
  PRIMARY KEY (item_id),
  FOREIGN KEY (customer_id) REFERENCES customers (customer_id)
    ON UPDATE CASCADE ON DELETE RESTRICT,
  FOREIGN KEY (product_sku) REFERENCES products (product_sku)
    ON UPDATE CASCADE ON DELETE RESTRICT,
  FOREIGN KEY (supplier_id) REFERENCES suppliers (supplier_id)
    ON UPDATE CASCADE ON DELETE RESTRICT
);

-- ─────────────────────────────────────────
-- ÍNDICES para mejorar rendimiento en JOINs
-- ─────────────────────────────────────────
CREATE INDEX IF NOT EXISTS idx_txn_id       ON transactions (transaction_id);
CREATE INDEX IF NOT EXISTS idx_txn_customer ON transactions (customer_id);
CREATE INDEX IF NOT EXISTS idx_txn_product  ON transactions (product_sku);
CREATE INDEX IF NOT EXISTS idx_txn_supplier ON transactions (supplier_id);